In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
###sentences
sent=['the glass of milk',
'the glass of juice',
'the cup of tea',
'I am a good boy',
'I am a good developer',
'understand the meaning of words',
'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
#Define the vocabulary size
voc_size=10000

In [7]:
##One hot represeentation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr


[[8054, 2167, 6369, 5037],
 [8054, 2167, 6369, 2685],
 [8054, 1411, 6369, 3293],
 [3983, 6470, 7253, 5107, 6359],
 [3983, 6470, 7253, 5107, 1312],
 [1362, 8054, 2213, 6369, 644],
 [5690, 4284, 4773, 5107]]

In [9]:
##Word Embedding representation system
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential


In [10]:
import numpy as np


In [12]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8054 2167 6369 5037]
 [   0    0    0    0 8054 2167 6369 2685]
 [   0    0    0    0 8054 1411 6369 3293]
 [   0    0    0 3983 6470 7253 5107 6359]
 [   0    0    0 3983 6470 7253 5107 1312]
 [   0    0    0 1362 8054 2213 6369  644]
 [   0    0    0    0 5690 4284 4773 5107]]


In [13]:
##Feautre Represrentation
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam', 'mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 175ms/step


array([[[-0.02121806, -0.00343259,  0.04679931, -0.04937316,
         -0.03026272,  0.00352894, -0.02456194,  0.0310287 ,
          0.02167894,  0.04970406],
        [-0.02121806, -0.00343259,  0.04679931, -0.04937316,
         -0.03026272,  0.00352894, -0.02456194,  0.0310287 ,
          0.02167894,  0.04970406],
        [-0.02121806, -0.00343259,  0.04679931, -0.04937316,
         -0.03026272,  0.00352894, -0.02456194,  0.0310287 ,
          0.02167894,  0.04970406],
        [-0.02121806, -0.00343259,  0.04679931, -0.04937316,
         -0.03026272,  0.00352894, -0.02456194,  0.0310287 ,
          0.02167894,  0.04970406],
        [ 0.011831  , -0.03016584,  0.00596075, -0.04235647,
          0.02361423, -0.01285575,  0.04571856, -0.04660922,
          0.02373279, -0.00988462],
        [-0.02262874,  0.0107011 ,  0.02716316, -0.00809987,
          0.02174537,  0.02420496, -0.0347976 , -0.01271088,
         -0.03358132, -0.00376892],
        [-0.01835853, -0.02806696,  0.01297886, -0.0

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 8054, 2167, 6369, 5037])

In [19]:
model.predict(embedded_docs[0])


1/1 [==============================] - 0s 34ms/step


array([[-0.02121806, -0.00343259,  0.04679931, -0.04937316, -0.03026272,
         0.00352894, -0.02456194,  0.0310287 ,  0.02167894,  0.04970406],
       [-0.02121806, -0.00343259,  0.04679931, -0.04937316, -0.03026272,
         0.00352894, -0.02456194,  0.0310287 ,  0.02167894,  0.04970406],
       [-0.02121806, -0.00343259,  0.04679931, -0.04937316, -0.03026272,
         0.00352894, -0.02456194,  0.0310287 ,  0.02167894,  0.04970406],
       [-0.02121806, -0.00343259,  0.04679931, -0.04937316, -0.03026272,
         0.00352894, -0.02456194,  0.0310287 ,  0.02167894,  0.04970406],
       [ 0.011831  , -0.03016584,  0.00596075, -0.04235647,  0.02361423,
        -0.01285575,  0.04571856, -0.04660922,  0.02373279, -0.00988462],
       [-0.02262874,  0.0107011 ,  0.02716316, -0.00809987,  0.02174537,
         0.02420496, -0.0347976 , -0.01271088, -0.03358132, -0.00376892],
       [-0.01835853, -0.02806696,  0.01297886, -0.04721545,  0.03248901,
         0.04181794, -0.02622336, -0.02672292